# Generated by Django 6.0.4 on 2026-04-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified_user_learning_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.track'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.track'),
        ),
    ]
