# Generated by Django 6.0.4 on 2026-04-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercontentprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['date_uploaded']},
        ),
    ]
