# Generated by Django 6.0.4 on 2026-04-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_content_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video Lesson'), ('LINK', 'External Link'), ('TEXT', 'Text Lesson')], max_length=10),
        ),
    ]
