# Generated by Django 6.0.4 on 2026-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_content_text_content_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
