# Generated by Django 6.0.4 on 2026-04-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assessment_is_locked_assessment_scheduled_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
