# Generated by Django 6.0.4 on 2026-04-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_classgroup_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
